import type { BlogPost } from './blog-data.types';

export const blogPosts: BlogPost[] = [
  {
    slug: 'como-proteger-contenido-academia-online',
    title: 'Cómo proteger el contenido de tu academia online en 2026',
    description: 'Descubre las mejores estrategias para evitar la piratería de vídeos educativos, proteger tu propiedad intelectual y asegurar los ingresos de tu academia.',
    date: '2026-03-15',
    readTime: '8 min',
    category: 'Protección',
    keywords: ['proteger contenido educativo', 'anti-piratería academia', 'seguridad vídeos online'],
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Pantalla de ordenador mostrando código de seguridad digital',
    toc: [
      { id: 'pirateria-en-numeros', label: 'La piratería educativa en números' },
      { id: 'marcas-de-agua-dinamicas', label: 'Marcas de agua dinámicas' },
      { id: 'control-sesiones', label: 'Control de sesiones simultáneas' },
      { id: 'streaming-sin-descarga', label: 'Streaming sin descarga' },
      { id: 'monitoreo-comportamiento', label: 'Monitoreo de comportamiento sospechoso' },
      { id: 'acuerdos-legales', label: 'Acuerdos legales claros' },
      { id: 'conclusion', label: 'Conclusión' },
    ],
  },
  {
    slug: 'cuentas-compartidas-problema-academias',
    title: 'Cuentas compartidas: el problema silencioso que arruina academias online',
    description: 'El 30% de los accesos a plataformas educativas son de cuentas compartidas. Aprende a detectarlo y solucionarlo sin perder estudiantes.',
    date: '2026-03-10',
    readTime: '6 min',
    category: 'Seguridad',
    keywords: ['cuentas compartidas educación', 'control acceso academia', 'sesiones simultáneas'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Múltiples dispositivos conectados representando cuentas compartidas',
    toc: [
      { id: 'cuanto-cuestan', label: '¿Cuánto te cuestan las cuentas compartidas?' },
      { id: 'por-que-no-detectan', label: 'Por qué las academias no lo detectan' },
      { id: 'senales', label: 'Señales de que tus cuentas se comparten' },
      { id: 'solucion', label: 'La solución: una sesión por estudiante' },
      { id: 'deteccion-inteligente', label: 'Detección inteligente' },
      { id: 'resultados-reales', label: 'Resultados reales' },
      { id: 'conclusion', label: 'Conclusión' },
    ],
  },
  {
    slug: 'guia-digitalizar-academia',
    title: 'Guía completa para digitalizar tu academia en 2026',
    description: 'Paso a paso para llevar tu academia presencial al mundo online: desde la grabación de vídeos hasta la gestión de estudiantes y pagos.',
    date: '2026-03-05',
    readTime: '10 min',
    category: 'Gestión',
    keywords: ['digitalizar academia', 'academia online', 'plataforma educativa', 'software para academias'],
    image: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Persona trabajando en la transformación digital de su negocio',
    toc: [
      { id: 'paso-1-estructura', label: 'Define tu estructura académica' },
      { id: 'paso-2-contenido', label: 'Graba contenido de calidad' },
      { id: 'paso-3-plataforma', label: 'Elige tu plataforma' },
      { id: 'paso-4-sube-contenido', label: 'Sube y organiza tu contenido' },
      { id: 'paso-5-equipo', label: 'Invita a tu equipo' },
      { id: 'paso-6-pagos', label: 'Configura los pagos' },
      { id: 'paso-7-directo', label: 'Clases en directo' },
      { id: 'paso-8-migracion', label: 'Migra tus estudiantes' },
      { id: 'conclusion', label: 'Conclusión' },
    ],
  },
  {
    slug: 'marca-de-agua-videos-educativos',
    title: 'Marca de agua en vídeos educativos: por qué es esencial para tu academia',
    description: 'Las marcas de agua dinámicas son la herramienta más efectiva contra la piratería educativa. Aprende cómo funcionan y por qué las necesitas.',
    date: '2026-02-28',
    readTime: '7 min',
    category: 'Protección',
    keywords: ['marca de agua vídeos', 'watermark educación', 'protección vídeos academia'],
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Grabación de vídeo profesional para contenido educativo',
    toc: [
      { id: 'que-es', label: '¿Qué es una marca de agua?' },
      { id: 'estatica-vs-dinamica', label: 'Estática vs. dinámica' },
      { id: 'por-que-no-basta', label: '¿Por qué no basta con impedir la descarga?' },
      { id: 'como-implementar', label: 'Cómo implementar marcas de agua' },
      { id: 'efecto-disuasorio', label: 'El efecto disuasorio' },
      { id: 'caso-practico', label: 'Caso práctico: academia de oposiciones' },
      { id: 'que-necesitas', label: '¿Qué necesitas para empezar?' },
      { id: 'conclusion', label: 'Conclusión' },
    ],
  },
  {
    slug: 'software-gestion-academias-que-necesitas',
    title: 'Software de gestión para academias: todo lo que necesitas en una plataforma',
    description: 'Comparativa y guía para elegir el mejor software de gestión académica. Profesores, estudiantes, clases, pagos y protección de contenido.',
    date: '2026-02-20',
    readTime: '9 min',
    category: 'Gestión',
    keywords: ['software gestión academias', 'plataforma gestión académica', 'LMS para academias'],
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Dashboard de software de gestión en pantalla de ordenador',
    toc: [
      { id: 'que-incluir', label: '¿Qué debe incluir?' },
      { id: 'comparativa', label: 'Comparativa de opciones en 2026' },
      { id: 'como-elegir', label: 'Cómo elegir el software correcto' },
      { id: 'coste-del-gratis', label: 'El coste real del "gratis"' },
      { id: 'conclusion', label: 'Conclusión' },
    ],
  },
  {
    slug: 'como-fijar-precio-academia-online',
    title: 'Cómo fijar el precio de tu academia online sin dejar dinero en la mesa',
    description: 'La mayoría de academias online cobran demasiado poco. Aprende a estructurar tus precios, elegir el modelo de suscripción adecuado y aumentar el valor percibido de tu oferta.',
    date: '2026-02-12',
    readTime: '8 min',
    category: 'Precios',
    keywords: ['precio academia online', 'modelo suscripción educación', 'tarifa academia', 'cuánto cobrar academia'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Calculadora y gráficos de precios sobre un escritorio',
    toc: [
      { id: 'error-de-precio', label: 'El error de fijar el precio por el tiempo' },
      { id: 'tres-modelos', label: 'Los tres modelos de precios' },
      { id: 'precio-bajo', label: '¿Tu precio es demasiado bajo?' },
      { id: 'aumentar-valor', label: 'Estrategias para aumentar el valor percibido' },
      { id: 'trampa-descuentos', label: 'La trampa de los descuentos' },
      { id: 'punto-de-partida', label: 'Un punto de partida práctico' },
    ],
  },
  {
    slug: 'reducir-abandono-estudiantes-academia',
    title: 'Cómo reducir el abandono de estudiantes en tu academia online',
    description: 'La tasa de finalización media en cursos online es menor del 15%. Estas estrategias han demostrado aumentar la retención de estudiantes sin necesidad de bajar precios.',
    date: '2026-02-05',
    readTime: '7 min',
    category: 'Gestión',
    keywords: ['retención estudiantes academia', 'abandono cursos online', 'engagement educativo'],
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Estudiantes participando activamente en una clase',
    toc: [
      { id: 'por-que-abandonan', label: 'Por qué abandonan los estudiantes' },
      { id: 'secuencia-bienvenida', label: 'La secuencia de bienvenida' },
      { id: 'modulos-cortos', label: 'Dividir en módulos cortos' },
      { id: 'clases-directo', label: 'Clases en directo periódicas' },
      { id: 'estudiantes-inactivos', label: 'Contactar estudiantes inactivos' },
      { id: 'comunidad', label: 'Comunidad entre estudiantes' },
      { id: 'metrica', label: 'La métrica que importa' },
    ],
  },
  {
    slug: 'clases-en-directo-vs-grabadas',
    title: 'Clases en directo vs. grabadas: qué modelo funciona mejor para tu academia',
    description: 'No existe una respuesta única. El modelo que más ingresos genera depende del tipo de contenido, tu audiencia y cómo gestionas el tiempo. Analizamos los dos enfoques.',
    date: '2026-01-28',
    readTime: '6 min',
    category: 'Gestión',
    keywords: ['clases en directo academia', 'clases grabadas vs directo', 'modelo híbrido educación online'],
    image: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Cámara profesional grabando una clase en directo',
    toc: [
      { id: 'ventajas-grabado', label: 'Ventajas del contenido grabado' },
      { id: 'ventajas-directo', label: 'Ventajas de las clases en directo' },
      { id: 'desventajas', label: 'Desventajas de cada modelo' },
      { id: 'modelo-hibrido', label: 'El modelo híbrido' },
      { id: 'como-decidir', label: 'Cómo decidir qué modelo elegir' },
    ],
  },
  {
    slug: 'errores-comunes-academia-online',
    title: 'Los 5 errores que destruyen academias online en los primeros seis meses',
    description: 'La mayoría de academias que fracasan cometen los mismos errores: lanzar demasiado tarde, subestimar la retención o elegir la plataforma equivocada. Aquí los analizamos uno a uno.',
    date: '2026-01-20',
    readTime: '9 min',
    category: 'Gestión',
    keywords: ['errores academia online', 'fracasar academia online', 'lanzar academia online'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Persona planificando estrategia con notas y documentos',
    toc: [
      { id: 'error-1', label: 'Esperar al producto perfecto' },
      { id: 'error-2', label: 'Elegir la plataforma equivocada' },
      { id: 'error-3', label: 'Ignorar la retención' },
      { id: 'error-4', label: 'No proteger el contenido' },
      { id: 'error-5', label: 'Fijar precios sin estrategia' },
      { id: 'denominador-comun', label: 'El denominador común' },
    ],
  },
  {
    slug: 'conseguir-primeros-estudiantes-academia',
    title: 'Cómo conseguir tus primeros 100 estudiantes en una academia online',
    description: 'El primer centenar de estudiantes es el más difícil. Estas son las acciones concretas —y el orden correcto para ejecutarlas— que funcionan sin necesidad de grandes presupuestos de marketing.',
    date: '2026-01-10',
    readTime: '10 min',
    category: 'Crecimiento',
    keywords: ['primeros estudiantes academia', 'marketing academia online', 'captar alumnos academia'],
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Grupo de estudiantes trabajando juntos en una academia',
    toc: [
      { id: 'paso-1-red', label: 'Empieza con tu red directa' },
      { id: 'paso-2-contenido', label: 'Publica contenido de valor' },
      { id: 'paso-3-demo', label: 'Sesión gratuita de demostración' },
      { id: 'paso-4-condiciones', label: 'Condiciones para primeros matriculados' },
      { id: 'paso-5-referencias', label: 'Pide referencias activamente' },
      { id: 'lo-que-no-funciona', label: 'Lo que no funciona en esta fase' },
      { id: 'objetivo-real', label: 'El objetivo real' },
    ],
  },
  {
    slug: 'crear-comunidad-estudiantes-academia-online',
    title: 'Cómo crear una comunidad de estudiantes que impulse tu academia online',
    description: 'Una comunidad activa reduce la tasa de abandono un 40% y multiplica el boca a boca. Aprende a construir un espacio donde tus estudiantes se motiven entre sí.',
    date: '2026-03-18',
    readTime: '8 min',
    category: 'Crecimiento',
    keywords: ['comunidad estudiantes online', 'fidelizar alumnos academia', 'engagement comunidad educativa'],
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Grupo de personas conectadas trabajando en comunidad',
    toc: [
      { id: 'retencion', label: 'Tu mejor herramienta de retención' },
      { id: 'canal', label: 'Elige el canal adecuado' },
      { id: 'rituales', label: 'Crea rituales de participación' },
      { id: 'empoderar', label: 'Empodera a los avanzados' },
      { id: 'medir', label: 'Mide lo que importa' },
      { id: 'boca-a-boca', label: 'El efecto boca a boca' },
    ],
  },
  {
    slug: 'seo-academias-online-atraer-estudiantes-google',
    title: 'SEO para academias online: cómo atraer estudiantes desde Google',
    description: 'El 68% de los estudiantes buscan academias en Google antes de inscribirse. Estas son las técnicas de SEO que funcionan específicamente para plataformas educativas.',
    date: '2026-03-19',
    readTime: '9 min',
    category: 'Crecimiento',
    keywords: ['SEO academia online', 'posicionamiento web educación', 'marketing orgánico academia', 'Google para academias'],
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Pantalla mostrando analíticas de tráfico web y SEO',
    toc: [
      { id: 'seo-vs-publicidad', label: 'SEO vs. publicidad' },
      { id: 'palabras-clave', label: 'Investiga las palabras clave' },
      { id: 'contenido', label: 'Contenido que responda preguntas' },
      { id: 'paginas-cursos', label: 'Optimiza páginas de cursos' },
      { id: 'seo-tecnico', label: 'SEO técnico' },
      { id: 'autoridad-enlaces', label: 'Construye autoridad con enlaces' },
      { id: 'mide-ajusta', label: 'Mide y ajusta cada mes' },
    ],
  },
];
