import * as XLSX from 'xlsx';

export interface ImportRow {
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  classNames: string;
  pagado?: boolean; // true = payment already collected (cash/transfer), skip in-app payment prompt
}

export interface ClassRow {
  name: string;
  price?: number;
  cuotas?: number;
  startDate?: string;
  teacherEmail?: string;
  description?: string;
  university?: string;
  carrera?: string;
  maxStudents?: number;
  whatsappGroupLink?: string;
}

export interface ImportResult {
  row: number;
  email: string;
  role: string;
  status: 'created' | 'skipped' | 'error';
  message: string;
  tempPassword?: string;
}

export interface ImportSummary {
  created: number;
  skipped: number;
  errors: number;
  total: number;
  classesCreated: number;
  classesUnmatched: number;
  classResults?: { name: string; status: 'created' | 'existed' | 'error'; message?: string }[];
  results: ImportResult[];
  quizzesCreated?: number;
  questionsCreated?: number;
  quizResults?: { quizName: string; courseName: string; questionsCount: number; status: 'created' | 'skipped' | 'error'; message?: string }[];
  documentsCreated?: number;
  pdfManifest?: PdfManifestEntry[];
}

export interface QuizRow {
  courseName: string;
  quizId: string;
  quizName: string;
  quizDescription: string;
}

export interface QuestionRow {
  quizId: string;
  questionId: string;
  questionText: string;
  answerId: string;
  answerText: string;
  isCorrect: number;
}

export interface FileRow {
  fileTitle: string;
  courseName: string;
  filename: string;
  filesize: string;
  filePath: string;
}

export interface PdfManifestEntry {
  fileTitle: string;
  courseName: string;
  filename: string;
  fileSizeKB: number;
  sitegroundPath: string;
}

/** Generated by scripts/ftp-to-r2.js — one entry per document already uploaded to R2 */
export interface DocumentManifestEntry {
  fileTitle: string;
  courseName: string;
  filename: string;
  filesize: number;
  contentType: string;
  r2Key: string;
  uploadId: string;
}

export function normalizeRows(rows: Record<string, unknown>[]): ImportRow[] {
  if (rows.length === 0) return [];
  const raw = rows[0];
  const keys = Object.keys(raw).map(k => k.toLowerCase().trim().replace(/\s*\(opcional\)/gi, '').trim());
  const find = (...names: string[]) => keys.findIndex(k => names.includes(k));

  const emailIdx = find('email');
  const firstIdx = find('firstname', 'nombre');
  const lastIdx = find('lastname', 'apellido', 'apellidos');
  const roleIdx = find('role', 'rol', 'moodle_rol');
  const classIdx = find('classes', 'clases', 'classnames', 'asignaturas', 'asignatura');
  const pagadoIdx = find('pagado', 'paid', 'pago recibido', 'ya pagado', 'ya_pagado');

  if (emailIdx === -1 || firstIdx === -1 || lastIdx === -1) return [];

  const TRUTHY = ['true', 'sí', 'si', '1', 'yes', 'x'];
  const origKeys = Object.keys(raw);
  return rows.map(row => ({
    email: String(row[origKeys[emailIdx]] ?? '').trim(),
    firstName: String(row[origKeys[firstIdx]] ?? '').trim(),
    lastName: String(row[origKeys[lastIdx]] ?? '').trim(),
    role: roleIdx !== -1 ? String(row[origKeys[roleIdx]] ?? 'STUDENT').trim() : 'STUDENT',
    classNames: classIdx !== -1 ? String(row[origKeys[classIdx]] ?? '').trim() : '',
    pagado: pagadoIdx !== -1 ? TRUTHY.includes(String(row[origKeys[pagadoIdx]] ?? '').toLowerCase().trim()) : false,
  })).filter(r => r.email);
}

/** Generic CSV parser — returns every row as a plain object keyed by header names. */
export function parseCSVGeneric(text: string): Record<string, unknown>[] {
  const splitLine = (line: string): string[] => {
    const fields: string[] = [];
    let current = '';
    let inQuotes = false;
    for (const ch of line) {
      if (ch === '"') { inQuotes = !inQuotes; continue; }
      if (ch === ',' && !inQuotes) { fields.push(current.trim()); current = ''; continue; }
      current += ch;
    }
    fields.push(current.trim());
    return fields;
  };

  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length < 2) return [];
  const headers = splitLine(lines[0]);
  return lines.slice(1).map(line => {
    const fields = splitLine(line);
    const obj: Record<string, unknown> = {};
    headers.forEach((h, i) => { obj[h] = fields[i] ?? ''; });
    return obj;
  });
}

export function parseCSV(text: string): ImportRow[] {
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length < 2) return [];

  const header = lines[0].split(',').map(h => h.trim().toLowerCase().replace(/\s*\(opcional\)/gi, '').trim());
  const emailIdx = header.findIndex(h => h === 'email');
  const firstIdx = header.findIndex(h => h === 'firstname' || h === 'nombre');
  const lastIdx = header.findIndex(h => h === 'lastname' || h === 'apellido' || h === 'apellidos');
  const roleIdx = header.findIndex(h => h === 'role' || h === 'rol');
  const classIdx = header.findIndex(h => ['classes', 'clases', 'classnames', 'asignaturas', 'asignatura'].includes(h));
  const pagadoIdx = header.findIndex(h => h === 'pagado' || h === 'paid' || h === 'pago recibido' || h === 'ya pagado');

  if (emailIdx === -1 || firstIdx === -1 || lastIdx === -1) return [];

  const TRUTHY = ['true', 'sí', 'si', '1', 'yes', 'x'];
  return lines.slice(1).map(line => {
    const fields: string[] = [];
    let current = '';
    let inQuotes = false;
    for (const ch of line) {
      if (ch === '"') { inQuotes = !inQuotes; continue; }
      if (ch === ',' && !inQuotes) { fields.push(current.trim()); current = ''; continue; }
      current += ch;
    }
    fields.push(current.trim());

    return {
      email: fields[emailIdx] || '',
      firstName: fields[firstIdx] || '',
      lastName: fields[lastIdx] || '',
      role: roleIdx !== -1 ? (fields[roleIdx] || 'STUDENT') : 'STUDENT',
      classNames: classIdx !== -1 ? (fields[classIdx] || '') : '',
      pagado: pagadoIdx !== -1 ? TRUTHY.includes((fields[pagadoIdx] || '').toLowerCase().trim()) : false,
    };
  }).filter(r => r.email);
}

// Re-export XLSX utilities needed by the modal
export { XLSX };

export function normalizeClassRows(rows: Record<string, unknown>[]): ClassRow[] {
  if (rows.length === 0) return [];
  const raw = rows[0];
  const keys = Object.keys(raw).map(k => k.toLowerCase().trim().replace(/\s*\(opcional\)/gi, '').trim().replace(/\s+/g, ''));
  const find = (...names: string[]) => keys.findIndex(k => names.includes(k));

  const nameIdx = find('nombre', 'name', 'clase', 'class', 'asignatura');
  if (nameIdx === -1) return [];

  const priceIdx = find('precio', 'price');
  const cuotasIdx = find('cuotas', 'numcuotas', 'installments', 'numpagos', 'pagos');
  const startDateIdx = find('fechainicio', 'startdate', 'inicio', 'start', 'fecha');
  const teacherIdx = find('profesoremail', 'teacheremail', 'emailprofesor', 'emailteacher', 'profesor', 'teacher');
  const descIdx = find('descripcion', 'description', 'desc');
  const universityIdx = find('universidad', 'university');
  const carreraIdx = find('carrera', 'degree', 'programa');
  const maxStudentsIdx = find('maxestudiantes', 'maxstudents', 'maxalumnos', 'capacidad', 'capacity');
  const whatsappIdx = find('whatsapp', 'whatsapplink', 'whatsappgrouplink', 'grupwhatsapp');

  const origKeys = Object.keys(raw);
  return rows.flatMap(row => {
    const name = String(row[origKeys[nameIdx]] ?? '').trim();
    if (!name) return [];
    const priceRaw = priceIdx !== -1 ? parseFloat(String(row[origKeys[priceIdx]] ?? '')) : NaN;
    const cuotasRaw = cuotasIdx !== -1 ? parseInt(String(row[origKeys[cuotasIdx]] ?? ''), 10) : NaN;
    const startDateRaw = startDateIdx !== -1 ? String(row[origKeys[startDateIdx]] ?? '').trim() : '';
    const teacherRaw = teacherIdx !== -1 ? String(row[origKeys[teacherIdx]] ?? '').trim().toLowerCase() : '';
    const descRaw = descIdx !== -1 ? String(row[origKeys[descIdx]] ?? '').trim() : '';
    const universityRaw = universityIdx !== -1 ? String(row[origKeys[universityIdx]] ?? '').trim() : '';
    const carreraRaw = carreraIdx !== -1 ? String(row[origKeys[carreraIdx]] ?? '').trim() : '';
    const maxStudentsRaw = maxStudentsIdx !== -1 ? parseInt(String(row[origKeys[maxStudentsIdx]] ?? ''), 10) : NaN;
    const whatsappRaw = whatsappIdx !== -1 ? String(row[origKeys[whatsappIdx]] ?? '').trim() : '';
    return [{
      name,
      price: isNaN(priceRaw) ? undefined : priceRaw,
      cuotas: isNaN(cuotasRaw) || cuotasRaw <= 0 ? undefined : cuotasRaw,
      startDate: startDateRaw || undefined,
      teacherEmail: teacherRaw || undefined,
      description: descRaw || undefined,
      university: universityRaw || undefined,
      carrera: carreraRaw || undefined,
      maxStudents: isNaN(maxStudentsRaw) ? undefined : maxStudentsRaw,
      whatsappGroupLink: whatsappRaw || undefined,
    }];
  });
}

/** Strip HTML tags and decode basic entities */
function stripHtml(str: string): string {
  return String(str || '')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim();
}

export function normalizeQuizRows(rows: Record<string, unknown>[]): QuizRow[] {
  if (rows.length === 0) return [];
  const raw = rows[0];
  const keys = Object.keys(raw).map(k => k.toLowerCase().trim().replace(/\s+/g, '').replace(/_/g, ''));
  const find = (...names: string[]) => keys.findIndex(k => names.includes(k));

  const courseIdx = find('coursename', 'curso', 'asignatura', 'course');
  const quizIdIdx = find('quizid', 'id');
  const quizNameIdx = find('quizname', 'nombre', 'name');
  const descIdx = find('quizdescription', 'description', 'descripcion');

  if (courseIdx === -1 || quizIdIdx === -1 || quizNameIdx === -1) return [];

  const origKeys = Object.keys(raw);
  return rows.flatMap(row => {
    const courseName = String(row[origKeys[courseIdx]] ?? '').trim();
    const quizId = String(row[origKeys[quizIdIdx]] ?? '').trim();
    const quizName = stripHtml(String(row[origKeys[quizNameIdx]] ?? '').trim());
    if (!courseName || !quizId || !quizName) return [];
    return [{
      courseName,
      quizId,
      quizName,
      quizDescription: descIdx !== -1 ? stripHtml(String(row[origKeys[descIdx]] ?? '')) : '',
    }];
  });
}

export function normalizeQuestionRows(rows: Record<string, unknown>[]): QuestionRow[] {
  if (rows.length === 0) return [];
  const raw = rows[0];
  const keys = Object.keys(raw).map(k => k.toLowerCase().trim().replace(/\s+/g, '').replace(/_/g, ''));
  const find = (...names: string[]) => keys.findIndex(k => names.includes(k));

  const quizIdIdx = find('quizid');
  const qIdIdx = find('questionid');
  const qTextIdx = find('questiontext', 'pregunta');
  const aIdIdx = find('answerid', 'respuestaid');
  const aTextIdx = find('answertext', 'respuesta');
  const correctIdx = find('iscorrect', 'correcta', 'correct');

  if (quizIdIdx === -1 || qIdIdx === -1 || qTextIdx === -1 || aIdIdx === -1 || aTextIdx === -1 || correctIdx === -1) return [];

  const origKeys = Object.keys(raw);
  return rows.flatMap(row => {
    const quizId = String(row[origKeys[quizIdIdx]] ?? '').trim();
    const questionId = String(row[origKeys[qIdIdx]] ?? '').trim();
    if (!quizId || !questionId) return [];
    return [{
      quizId,
      questionId,
      questionText: stripHtml(String(row[origKeys[qTextIdx]] ?? '')),
      answerId: String(row[origKeys[aIdIdx]] ?? '').trim(),
      answerText: stripHtml(String(row[origKeys[aTextIdx]] ?? '')),
      isCorrect: parseFloat(String(row[origKeys[correctIdx]] ?? '0')),
    }];
  });
}

export function normalizeFileRows(rows: Record<string, unknown>[]): FileRow[] {
  if (rows.length === 0) return [];
  const raw = rows[0];
  const keys = Object.keys(raw).map(k => k.toLowerCase().trim().replace(/\s+/g, '').replace(/_/g, ''));
  const find = (...names: string[]) => keys.findIndex(k => names.includes(k));

  const titleIdx = find('filetitle', 'titulo', 'title', 'nombre', 'name');
  const courseIdx = find('coursename', 'curso', 'asignatura', 'course');
  const filenameIdx = find('filename', 'archivo', 'file');
  const sizeIdx = find('filesize', 'tamano', 'size');
  const pathIdx = find('filepath', 'path', 'ruta');

  if (titleIdx === -1 || courseIdx === -1 || filenameIdx === -1 || pathIdx === -1) return [];

  const origKeys = Object.keys(raw);
  return rows.flatMap(row => {
    const fileTitle = String(row[origKeys[titleIdx]] ?? '').trim();
    const courseName = String(row[origKeys[courseIdx]] ?? '').trim();
    const filename = String(row[origKeys[filenameIdx]] ?? '').trim();
    const filePath = String(row[origKeys[pathIdx]] ?? '').trim();
    if (!fileTitle || !courseName || !filename || !filePath) return [];
    return [{
      fileTitle,
      courseName,
      filename,
      filesize: String(row[origKeys[sizeIdx]] ?? '0'),
      filePath,
    }];
  });
}
